### ISSUE TITLE
Create a Makefile to make the life easy for newbies

### ISSUE THREAD

**Issue by ryukinix** [xi-frontend/xim#7]
The current build instructions is not great. Too many steps. `make && make install` is better.

**Comment by rafaelcn** [comment]
To elaborate a little:

  The current flow of the installation of `xi-editor`, the back-end, and `xim`, the front-end, is not so good. You have first to clone and install `xi-editor` with some three steps and some more to install syntax highlight, along with xim, which is approximately the same number of steps. 
  What we are thinking is:

1. Add `xi-editor` as a submodule to `xim`
2. Create a make that will make all of those steps in one `make && make install`.

**Comment by ryukinix** [comment]
This issue was moved to xi-frontend/xim-#7
